// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workflow_plugin_control_plane/envelopes/v1alpha1/control_plane_envelopes.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlPlaneEnvelope struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion    string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	EnvelopeId         string                 `protobuf:"bytes,2,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	Kind               string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	TenantHandle       string                 `protobuf:"bytes,4,opt,name=tenant_handle,json=tenantHandle,proto3" json:"tenant_handle,omitempty"`
	ActorHandle        string                 `protobuf:"bytes,5,opt,name=actor_handle,json=actorHandle,proto3" json:"actor_handle,omitempty"`
	ResourceHandle     string                 `protobuf:"bytes,6,opt,name=resource_handle,json=resourceHandle,proto3" json:"resource_handle,omitempty"`
	CorrelationId      string                 `protobuf:"bytes,7,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	OccurredAtUnixNano int64                  `protobuf:"varint,8,opt,name=occurred_at_unix_nano,json=occurredAtUnixNano,proto3" json:"occurred_at_unix_nano,omitempty"`
	ObservedAtUnixNano int64                  `protobuf:"varint,9,opt,name=observed_at_unix_nano,json=observedAtUnixNano,proto3" json:"observed_at_unix_nano,omitempty"`
	Retention          *RetentionMetadata     `protobuf:"bytes,10,opt,name=retention,proto3" json:"retention,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ControlPlaneEnvelope) Reset() {
	*x = ControlPlaneEnvelope{}
	mi := &file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlPlaneEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlPlaneEnvelope) ProtoMessage() {}

func (x *ControlPlaneEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlPlaneEnvelope.ProtoReflect.Descriptor instead.
func (*ControlPlaneEnvelope) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDescGZIP(), []int{0}
}

func (x *ControlPlaneEnvelope) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *ControlPlaneEnvelope) GetEnvelopeId() string {
	if x != nil {
		return x.EnvelopeId
	}
	return ""
}

func (x *ControlPlaneEnvelope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ControlPlaneEnvelope) GetTenantHandle() string {
	if x != nil {
		return x.TenantHandle
	}
	return ""
}

func (x *ControlPlaneEnvelope) GetActorHandle() string {
	if x != nil {
		return x.ActorHandle
	}
	return ""
}

func (x *ControlPlaneEnvelope) GetResourceHandle() string {
	if x != nil {
		return x.ResourceHandle
	}
	return ""
}

func (x *ControlPlaneEnvelope) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *ControlPlaneEnvelope) GetOccurredAtUnixNano() int64 {
	if x != nil {
		return x.OccurredAtUnixNano
	}
	return 0
}

func (x *ControlPlaneEnvelope) GetObservedAtUnixNano() int64 {
	if x != nil {
		return x.ObservedAtUnixNano
	}
	return 0
}

func (x *ControlPlaneEnvelope) GetRetention() *RetentionMetadata {
	if x != nil {
		return x.Retention
	}
	return nil
}

type RetentionMetadata struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	RedactionState             string                 `protobuf:"bytes,1,opt,name=redaction_state,json=redactionState,proto3" json:"redaction_state,omitempty"`
	RetentionExpiresAtUnixNano int64                  `protobuf:"varint,2,opt,name=retention_expires_at_unix_nano,json=retentionExpiresAtUnixNano,proto3" json:"retention_expires_at_unix_nano,omitempty"`
	Tombstoned                 bool                   `protobuf:"varint,3,opt,name=tombstoned,proto3" json:"tombstoned,omitempty"`
	LegalErasure               bool                   `protobuf:"varint,4,opt,name=legal_erasure,json=legalErasure,proto3" json:"legal_erasure,omitempty"`
	CorrelationRekeyId         string                 `protobuf:"bytes,5,opt,name=correlation_rekey_id,json=correlationRekeyId,proto3" json:"correlation_rekey_id,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RetentionMetadata) Reset() {
	*x = RetentionMetadata{}
	mi := &file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetentionMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetentionMetadata) ProtoMessage() {}

func (x *RetentionMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetentionMetadata.ProtoReflect.Descriptor instead.
func (*RetentionMetadata) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDescGZIP(), []int{1}
}

func (x *RetentionMetadata) GetRedactionState() string {
	if x != nil {
		return x.RedactionState
	}
	return ""
}

func (x *RetentionMetadata) GetRetentionExpiresAtUnixNano() int64 {
	if x != nil {
		return x.RetentionExpiresAtUnixNano
	}
	return 0
}

func (x *RetentionMetadata) GetTombstoned() bool {
	if x != nil {
		return x.Tombstoned
	}
	return false
}

func (x *RetentionMetadata) GetLegalErasure() bool {
	if x != nil {
		return x.LegalErasure
	}
	return false
}

func (x *RetentionMetadata) GetCorrelationRekeyId() string {
	if x != nil {
		return x.CorrelationRekeyId
	}
	return ""
}

var File_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto protoreflect.FileDescriptor

const file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDesc = "" +
	"\n" +
	"Nworkflow_plugin_control_plane/envelopes/v1alpha1/control_plane_envelopes.proto\x120workflow_plugin_control_plane.envelopes.v1alpha1\"\xd7\x03\n" +
	"\x14ControlPlaneEnvelope\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1f\n" +
	"\venvelope_id\x18\x02 \x01(\tR\n" +
	"envelopeId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12#\n" +
	"\rtenant_handle\x18\x04 \x01(\tR\ftenantHandle\x12!\n" +
	"\factor_handle\x18\x05 \x01(\tR\vactorHandle\x12'\n" +
	"\x0fresource_handle\x18\x06 \x01(\tR\x0eresourceHandle\x12%\n" +
	"\x0ecorrelation_id\x18\a \x01(\tR\rcorrelationId\x121\n" +
	"\x15occurred_at_unix_nano\x18\b \x01(\x03R\x12occurredAtUnixNano\x121\n" +
	"\x15observed_at_unix_nano\x18\t \x01(\x03R\x12observedAtUnixNano\x12a\n" +
	"\tretention\x18\n" +
	" \x01(\v2C.workflow_plugin_control_plane.envelopes.v1alpha1.RetentionMetadataR\tretention\"\xf7\x01\n" +
	"\x11RetentionMetadata\x12'\n" +
	"\x0fredaction_state\x18\x01 \x01(\tR\x0eredactionState\x12B\n" +
	"\x1eretention_expires_at_unix_nano\x18\x02 \x01(\x03R\x1aretentionExpiresAtUnixNano\x12\x1e\n" +
	"\n" +
	"tombstoned\x18\x03 \x01(\bR\n" +
	"tombstoned\x12#\n" +
	"\rlegal_erasure\x18\x04 \x01(\bR\flegalErasure\x120\n" +
	"\x14correlation_rekey_id\x18\x05 \x01(\tR\x12correlationRekeyIdBFZDgithub.com/GoCodeAlone/workflow-plugin-control-plane/envelopes/pb;pbb\x06proto3"

var (
	file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDescOnce sync.Once
	file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDescData []byte
)

func file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDescGZIP() []byte {
	file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDescOnce.Do(func() {
		file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDesc), len(file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDesc)))
	})
	return file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDescData
}

var file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_goTypes = []any{
	(*ControlPlaneEnvelope)(nil), // 0: workflow_plugin_control_plane.envelopes.v1alpha1.ControlPlaneEnvelope
	(*RetentionMetadata)(nil),    // 1: workflow_plugin_control_plane.envelopes.v1alpha1.RetentionMetadata
}
var file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_depIdxs = []int32{
	1, // 0: workflow_plugin_control_plane.envelopes.v1alpha1.ControlPlaneEnvelope.retention:type_name -> workflow_plugin_control_plane.envelopes.v1alpha1.RetentionMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_init()
}
func file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_init() {
	if File_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDesc), len(file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_goTypes,
		DependencyIndexes: file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_depIdxs,
		MessageInfos:      file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_msgTypes,
	}.Build()
	File_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto = out.File
	file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_goTypes = nil
	file_workflow_plugin_control_plane_envelopes_v1alpha1_control_plane_envelopes_proto_depIdxs = nil
}
