// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workflow_plugin_control_plane/descriptors/v1alpha1/control_plane_descriptors.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteActionDescriptor struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion    string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	DescriptorId       string                 `protobuf:"bytes,2,opt,name=descriptor_id,json=descriptorId,proto3" json:"descriptor_id,omitempty"`
	OperationId        string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	RouteHandle        string                 `protobuf:"bytes,4,opt,name=route_handle,json=routeHandle,proto3" json:"route_handle,omitempty"`
	AuthClassRef       string                 `protobuf:"bytes,5,opt,name=auth_class_ref,json=authClassRef,proto3" json:"auth_class_ref,omitempty"`
	AuditClassRef      string                 `protobuf:"bytes,6,opt,name=audit_class_ref,json=auditClassRef,proto3" json:"audit_class_ref,omitempty"`
	InputSchemaDigest  string                 `protobuf:"bytes,7,opt,name=input_schema_digest,json=inputSchemaDigest,proto3" json:"input_schema_digest,omitempty"`
	OutputSchemaDigest string                 `protobuf:"bytes,8,opt,name=output_schema_digest,json=outputSchemaDigest,proto3" json:"output_schema_digest,omitempty"`
	ProviderHandoff    *ProviderHandoffRef    `protobuf:"bytes,9,opt,name=provider_handoff,json=providerHandoff,proto3" json:"provider_handoff,omitempty"`
	Admin              *AdminContribution     `protobuf:"bytes,10,opt,name=admin,proto3" json:"admin,omitempty"`
	PresentationRef    string                 `protobuf:"bytes,11,opt,name=presentation_ref,json=presentationRef,proto3" json:"presentation_ref,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RouteActionDescriptor) Reset() {
	*x = RouteActionDescriptor{}
	mi := &file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteActionDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteActionDescriptor) ProtoMessage() {}

func (x *RouteActionDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteActionDescriptor.ProtoReflect.Descriptor instead.
func (*RouteActionDescriptor) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDescGZIP(), []int{0}
}

func (x *RouteActionDescriptor) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *RouteActionDescriptor) GetDescriptorId() string {
	if x != nil {
		return x.DescriptorId
	}
	return ""
}

func (x *RouteActionDescriptor) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RouteActionDescriptor) GetRouteHandle() string {
	if x != nil {
		return x.RouteHandle
	}
	return ""
}

func (x *RouteActionDescriptor) GetAuthClassRef() string {
	if x != nil {
		return x.AuthClassRef
	}
	return ""
}

func (x *RouteActionDescriptor) GetAuditClassRef() string {
	if x != nil {
		return x.AuditClassRef
	}
	return ""
}

func (x *RouteActionDescriptor) GetInputSchemaDigest() string {
	if x != nil {
		return x.InputSchemaDigest
	}
	return ""
}

func (x *RouteActionDescriptor) GetOutputSchemaDigest() string {
	if x != nil {
		return x.OutputSchemaDigest
	}
	return ""
}

func (x *RouteActionDescriptor) GetProviderHandoff() *ProviderHandoffRef {
	if x != nil {
		return x.ProviderHandoff
	}
	return nil
}

func (x *RouteActionDescriptor) GetAdmin() *AdminContribution {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *RouteActionDescriptor) GetPresentationRef() string {
	if x != nil {
		return x.PresentationRef
	}
	return ""
}

type ProviderHandoffRef struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ProviderPluginId      string                 `protobuf:"bytes,1,opt,name=provider_plugin_id,json=providerPluginId,proto3" json:"provider_plugin_id,omitempty"`
	ProviderPluginVersion string                 `protobuf:"bytes,2,opt,name=provider_plugin_version,json=providerPluginVersion,proto3" json:"provider_plugin_version,omitempty"`
	CapabilityId          string                 `protobuf:"bytes,3,opt,name=capability_id,json=capabilityId,proto3" json:"capability_id,omitempty"`
	CapabilityVersion     string                 `protobuf:"bytes,4,opt,name=capability_version,json=capabilityVersion,proto3" json:"capability_version,omitempty"`
	InputSchemaDigest     string                 `protobuf:"bytes,5,opt,name=input_schema_digest,json=inputSchemaDigest,proto3" json:"input_schema_digest,omitempty"`
	ActionNonce           string                 `protobuf:"bytes,6,opt,name=action_nonce,json=actionNonce,proto3" json:"action_nonce,omitempty"`
	IdempotencyKey        string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ProviderHandoffRef) Reset() {
	*x = ProviderHandoffRef{}
	mi := &file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderHandoffRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderHandoffRef) ProtoMessage() {}

func (x *ProviderHandoffRef) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderHandoffRef.ProtoReflect.Descriptor instead.
func (*ProviderHandoffRef) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderHandoffRef) GetProviderPluginId() string {
	if x != nil {
		return x.ProviderPluginId
	}
	return ""
}

func (x *ProviderHandoffRef) GetProviderPluginVersion() string {
	if x != nil {
		return x.ProviderPluginVersion
	}
	return ""
}

func (x *ProviderHandoffRef) GetCapabilityId() string {
	if x != nil {
		return x.CapabilityId
	}
	return ""
}

func (x *ProviderHandoffRef) GetCapabilityVersion() string {
	if x != nil {
		return x.CapabilityVersion
	}
	return ""
}

func (x *ProviderHandoffRef) GetInputSchemaDigest() string {
	if x != nil {
		return x.InputSchemaDigest
	}
	return ""
}

func (x *ProviderHandoffRef) GetActionNonce() string {
	if x != nil {
		return x.ActionNonce
	}
	return ""
}

func (x *ProviderHandoffRef) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type AdminContribution struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	ResourceRef                      string                 `protobuf:"bytes,1,opt,name=resource_ref,json=resourceRef,proto3" json:"resource_ref,omitempty"`
	ActionClassRef                   string                 `protobuf:"bytes,2,opt,name=action_class_ref,json=actionClassRef,proto3" json:"action_class_ref,omitempty"`
	RiskRef                          string                 `protobuf:"bytes,3,opt,name=risk_ref,json=riskRef,proto3" json:"risk_ref,omitempty"`
	SeverityRef                      string                 `protobuf:"bytes,4,opt,name=severity_ref,json=severityRef,proto3" json:"severity_ref,omitempty"`
	PermissionExplanationTemplateRef string                 `protobuf:"bytes,5,opt,name=permission_explanation_template_ref,json=permissionExplanationTemplateRef,proto3" json:"permission_explanation_template_ref,omitempty"`
	RenderRef                        string                 `protobuf:"bytes,6,opt,name=render_ref,json=renderRef,proto3" json:"render_ref,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *AdminContribution) Reset() {
	*x = AdminContribution{}
	mi := &file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminContribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminContribution) ProtoMessage() {}

func (x *AdminContribution) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminContribution.ProtoReflect.Descriptor instead.
func (*AdminContribution) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDescGZIP(), []int{2}
}

func (x *AdminContribution) GetResourceRef() string {
	if x != nil {
		return x.ResourceRef
	}
	return ""
}

func (x *AdminContribution) GetActionClassRef() string {
	if x != nil {
		return x.ActionClassRef
	}
	return ""
}

func (x *AdminContribution) GetRiskRef() string {
	if x != nil {
		return x.RiskRef
	}
	return ""
}

func (x *AdminContribution) GetSeverityRef() string {
	if x != nil {
		return x.SeverityRef
	}
	return ""
}

func (x *AdminContribution) GetPermissionExplanationTemplateRef() string {
	if x != nil {
		return x.PermissionExplanationTemplateRef
	}
	return ""
}

func (x *AdminContribution) GetRenderRef() string {
	if x != nil {
		return x.RenderRef
	}
	return ""
}

var File_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto protoreflect.FileDescriptor

const file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDesc = "" +
	"\n" +
	"Rworkflow_plugin_control_plane/descriptors/v1alpha1/control_plane_descriptors.proto\x122workflow_plugin_control_plane.descriptors.v1alpha1\"\xd8\x04\n" +
	"\x15RouteActionDescriptor\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12#\n" +
	"\rdescriptor_id\x18\x02 \x01(\tR\fdescriptorId\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12!\n" +
	"\froute_handle\x18\x04 \x01(\tR\vrouteHandle\x12$\n" +
	"\x0eauth_class_ref\x18\x05 \x01(\tR\fauthClassRef\x12&\n" +
	"\x0faudit_class_ref\x18\x06 \x01(\tR\rauditClassRef\x12.\n" +
	"\x13input_schema_digest\x18\a \x01(\tR\x11inputSchemaDigest\x120\n" +
	"\x14output_schema_digest\x18\b \x01(\tR\x12outputSchemaDigest\x12q\n" +
	"\x10provider_handoff\x18\t \x01(\v2F.workflow_plugin_control_plane.descriptors.v1alpha1.ProviderHandoffRefR\x0fproviderHandoff\x12[\n" +
	"\x05admin\x18\n" +
	" \x01(\v2E.workflow_plugin_control_plane.descriptors.v1alpha1.AdminContributionR\x05admin\x12)\n" +
	"\x10presentation_ref\x18\v \x01(\tR\x0fpresentationRef\"\xca\x02\n" +
	"\x12ProviderHandoffRef\x12,\n" +
	"\x12provider_plugin_id\x18\x01 \x01(\tR\x10providerPluginId\x126\n" +
	"\x17provider_plugin_version\x18\x02 \x01(\tR\x15providerPluginVersion\x12#\n" +
	"\rcapability_id\x18\x03 \x01(\tR\fcapabilityId\x12-\n" +
	"\x12capability_version\x18\x04 \x01(\tR\x11capabilityVersion\x12.\n" +
	"\x13input_schema_digest\x18\x05 \x01(\tR\x11inputSchemaDigest\x12!\n" +
	"\faction_nonce\x18\x06 \x01(\tR\vactionNonce\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"\x8c\x02\n" +
	"\x11AdminContribution\x12!\n" +
	"\fresource_ref\x18\x01 \x01(\tR\vresourceRef\x12(\n" +
	"\x10action_class_ref\x18\x02 \x01(\tR\x0eactionClassRef\x12\x19\n" +
	"\brisk_ref\x18\x03 \x01(\tR\ariskRef\x12!\n" +
	"\fseverity_ref\x18\x04 \x01(\tR\vseverityRef\x12M\n" +
	"#permission_explanation_template_ref\x18\x05 \x01(\tR permissionExplanationTemplateRef\x12\x1d\n" +
	"\n" +
	"render_ref\x18\x06 \x01(\tR\trenderRefBHZFgithub.com/GoCodeAlone/workflow-plugin-control-plane/descriptors/pb;pbb\x06proto3"

var (
	file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDescOnce sync.Once
	file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDescData []byte
)

func file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDescGZIP() []byte {
	file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDescOnce.Do(func() {
		file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDesc), len(file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDesc)))
	})
	return file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDescData
}

var file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_goTypes = []any{
	(*RouteActionDescriptor)(nil), // 0: workflow_plugin_control_plane.descriptors.v1alpha1.RouteActionDescriptor
	(*ProviderHandoffRef)(nil),    // 1: workflow_plugin_control_plane.descriptors.v1alpha1.ProviderHandoffRef
	(*AdminContribution)(nil),     // 2: workflow_plugin_control_plane.descriptors.v1alpha1.AdminContribution
}
var file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_depIdxs = []int32{
	1, // 0: workflow_plugin_control_plane.descriptors.v1alpha1.RouteActionDescriptor.provider_handoff:type_name -> workflow_plugin_control_plane.descriptors.v1alpha1.ProviderHandoffRef
	2, // 1: workflow_plugin_control_plane.descriptors.v1alpha1.RouteActionDescriptor.admin:type_name -> workflow_plugin_control_plane.descriptors.v1alpha1.AdminContribution
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() {
	file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_init()
}
func file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_init() {
	if File_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDesc), len(file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_goTypes,
		DependencyIndexes: file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_depIdxs,
		MessageInfos:      file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_msgTypes,
	}.Build()
	File_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto = out.File
	file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_goTypes = nil
	file_workflow_plugin_control_plane_descriptors_v1alpha1_control_plane_descriptors_proto_depIdxs = nil
}
