// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: workflow_plugin_control_plane/registry/v1alpha1/control_plane_registry.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescriptorRegistration struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion              string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	DescriptorDigest             string                 `protobuf:"bytes,2,opt,name=descriptor_digest,json=descriptorDigest,proto3" json:"descriptor_digest,omitempty"`
	SchemaDigest                 string                 `protobuf:"bytes,3,opt,name=schema_digest,json=schemaDigest,proto3" json:"schema_digest,omitempty"`
	PluginId                     string                 `protobuf:"bytes,4,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	PluginVersion                string                 `protobuf:"bytes,5,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	PluginPackageDigest          string                 `protobuf:"bytes,6,opt,name=plugin_package_digest,json=pluginPackageDigest,proto3" json:"plugin_package_digest,omitempty"`
	SigningRootRef               string                 `protobuf:"bytes,7,opt,name=signing_root_ref,json=signingRootRef,proto3" json:"signing_root_ref,omitempty"`
	ProvenanceSource             string                 `protobuf:"bytes,8,opt,name=provenance_source,json=provenanceSource,proto3" json:"provenance_source,omitempty"`
	AllowlistEpoch               uint64                 `protobuf:"varint,9,opt,name=allowlist_epoch,json=allowlistEpoch,proto3" json:"allowlist_epoch,omitempty"`
	DowngradeFloorVersion        string                 `protobuf:"bytes,10,opt,name=downgrade_floor_version,json=downgradeFloorVersion,proto3" json:"downgrade_floor_version,omitempty"`
	RevocationFreshUntilUnixNano int64                  `protobuf:"varint,11,opt,name=revocation_fresh_until_unix_nano,json=revocationFreshUntilUnixNano,proto3" json:"revocation_fresh_until_unix_nano,omitempty"`
	FetchedAtUnixNano            int64                  `protobuf:"varint,12,opt,name=fetched_at_unix_nano,json=fetchedAtUnixNano,proto3" json:"fetched_at_unix_nano,omitempty"`
	ValidatedAtUnixNano          int64                  `protobuf:"varint,13,opt,name=validated_at_unix_nano,json=validatedAtUnixNano,proto3" json:"validated_at_unix_nano,omitempty"`
	ParserCompatibilityVersion   string                 `protobuf:"bytes,14,opt,name=parser_compatibility_version,json=parserCompatibilityVersion,proto3" json:"parser_compatibility_version,omitempty"`
	TrustRootGeneration          uint64                 `protobuf:"varint,15,opt,name=trust_root_generation,json=trustRootGeneration,proto3" json:"trust_root_generation,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *DescriptorRegistration) Reset() {
	*x = DescriptorRegistration{}
	mi := &file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescriptorRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescriptorRegistration) ProtoMessage() {}

func (x *DescriptorRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescriptorRegistration.ProtoReflect.Descriptor instead.
func (*DescriptorRegistration) Descriptor() ([]byte, []int) {
	return file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_rawDescGZIP(), []int{0}
}

func (x *DescriptorRegistration) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *DescriptorRegistration) GetDescriptorDigest() string {
	if x != nil {
		return x.DescriptorDigest
	}
	return ""
}

func (x *DescriptorRegistration) GetSchemaDigest() string {
	if x != nil {
		return x.SchemaDigest
	}
	return ""
}

func (x *DescriptorRegistration) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *DescriptorRegistration) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *DescriptorRegistration) GetPluginPackageDigest() string {
	if x != nil {
		return x.PluginPackageDigest
	}
	return ""
}

func (x *DescriptorRegistration) GetSigningRootRef() string {
	if x != nil {
		return x.SigningRootRef
	}
	return ""
}

func (x *DescriptorRegistration) GetProvenanceSource() string {
	if x != nil {
		return x.ProvenanceSource
	}
	return ""
}

func (x *DescriptorRegistration) GetAllowlistEpoch() uint64 {
	if x != nil {
		return x.AllowlistEpoch
	}
	return 0
}

func (x *DescriptorRegistration) GetDowngradeFloorVersion() string {
	if x != nil {
		return x.DowngradeFloorVersion
	}
	return ""
}

func (x *DescriptorRegistration) GetRevocationFreshUntilUnixNano() int64 {
	if x != nil {
		return x.RevocationFreshUntilUnixNano
	}
	return 0
}

func (x *DescriptorRegistration) GetFetchedAtUnixNano() int64 {
	if x != nil {
		return x.FetchedAtUnixNano
	}
	return 0
}

func (x *DescriptorRegistration) GetValidatedAtUnixNano() int64 {
	if x != nil {
		return x.ValidatedAtUnixNano
	}
	return 0
}

func (x *DescriptorRegistration) GetParserCompatibilityVersion() string {
	if x != nil {
		return x.ParserCompatibilityVersion
	}
	return ""
}

func (x *DescriptorRegistration) GetTrustRootGeneration() uint64 {
	if x != nil {
		return x.TrustRootGeneration
	}
	return 0
}

var File_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto protoreflect.FileDescriptor

const file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_rawDesc = "" +
	"\n" +
	"Lworkflow_plugin_control_plane/registry/v1alpha1/control_plane_registry.proto\x12/workflow_plugin_control_plane.registry.v1alpha1\"\xe9\x05\n" +
	"\x16DescriptorRegistration\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12+\n" +
	"\x11descriptor_digest\x18\x02 \x01(\tR\x10descriptorDigest\x12#\n" +
	"\rschema_digest\x18\x03 \x01(\tR\fschemaDigest\x12\x1b\n" +
	"\tplugin_id\x18\x04 \x01(\tR\bpluginId\x12%\n" +
	"\x0eplugin_version\x18\x05 \x01(\tR\rpluginVersion\x122\n" +
	"\x15plugin_package_digest\x18\x06 \x01(\tR\x13pluginPackageDigest\x12(\n" +
	"\x10signing_root_ref\x18\a \x01(\tR\x0esigningRootRef\x12+\n" +
	"\x11provenance_source\x18\b \x01(\tR\x10provenanceSource\x12'\n" +
	"\x0fallowlist_epoch\x18\t \x01(\x04R\x0eallowlistEpoch\x126\n" +
	"\x17downgrade_floor_version\x18\n" +
	" \x01(\tR\x15downgradeFloorVersion\x12F\n" +
	" revocation_fresh_until_unix_nano\x18\v \x01(\x03R\x1crevocationFreshUntilUnixNano\x12/\n" +
	"\x14fetched_at_unix_nano\x18\f \x01(\x03R\x11fetchedAtUnixNano\x123\n" +
	"\x16validated_at_unix_nano\x18\r \x01(\x03R\x13validatedAtUnixNano\x12@\n" +
	"\x1cparser_compatibility_version\x18\x0e \x01(\tR\x1aparserCompatibilityVersion\x122\n" +
	"\x15trust_root_generation\x18\x0f \x01(\x04R\x13trustRootGenerationBEZCgithub.com/GoCodeAlone/workflow-plugin-control-plane/registry/pb;pbb\x06proto3"

var (
	file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_rawDescOnce sync.Once
	file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_rawDescData []byte
)

func file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_rawDescGZIP() []byte {
	file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_rawDescOnce.Do(func() {
		file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_rawDesc), len(file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_rawDesc)))
	})
	return file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_rawDescData
}

var file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_goTypes = []any{
	(*DescriptorRegistration)(nil), // 0: workflow_plugin_control_plane.registry.v1alpha1.DescriptorRegistration
}
var file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_init() }
func file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_init() {
	if File_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_rawDesc), len(file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_goTypes,
		DependencyIndexes: file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_depIdxs,
		MessageInfos:      file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_msgTypes,
	}.Build()
	File_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto = out.File
	file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_goTypes = nil
	file_workflow_plugin_control_plane_registry_v1alpha1_control_plane_registry_proto_depIdxs = nil
}
